const questions = {
    dreams: [
        "Jakie jest twoje największe niespełnione marzenie?",
        "Czy uważasz, że masz określone przeznaczenie?",
        "Co byś zrobiła, gdybyś wiedziała, że nie możesz ponieść porażki?",
        "... (36 więcej)",
                "Czy uważasz, że masz określone przeznaczenie?",
                "Gdybyś mogła żyć w innym czasie i miejscu, gdzie by to było?",
                "Czy myślisz, że każdy człowiek ma swoją misję w życiu?",
                "Co byś zrobiła, gdybyś wiedziała, że nie możesz ponieść porażki?",
                "Jakie jedno wydarzenie mogłoby odmienić twoje życie?",
                "Gdybyś mogła nauczyć się jednej nowej umiejętności w jedną noc, co by to było?",
                "Jakie pytanie o przyszłość chciałabyś znać odpowiedź?",
                "Czy myślisz, że wszechświat ma jakiś ukryty sens?",
                "Gdybyś mogła dostać znak od losu, co chciałabyś, aby ci powiedział?",
                "Co jest dla ciebie ważniejsze – stabilizacja czy ekscytujące życie pełne ryzyka?",
                "Czy uważasz, że myśli mają moc kształtowania rzeczywistości?",
                "Jaki sen powtarzał się w twoim życiu najczęściej?",
                "Co sądzisz o przeznaczeniu – istnieje, czy to my je tworzymy?",
                "Czy kiedykolwiek miałaś wrażenie, że coś w twoim życiu wydarzyło się 'nieprzypadkowo'?",
                "Jak wyobrażasz sobie swoje idealne życie za 10 lat?",
                "Czy kiedykolwiek podjęłaś decyzję, która wydawała się irracjonalna, ale była słuszna?",
                "Jak myślisz, czy istnieją równoległe światy?",
                "Czy kiedykolwiek miałaś przeczucie, które okazało się prawdziwe?",
                "Czy wierzysz w karmę?",
                "Czy jest coś, co czujesz, że musisz jeszcze zrobić w tym życiu?",
                "Jaka myśl sprawia, że czujesz największą motywację?",
                "Czy masz jakieś nierozwiązane marzenie z dzieciństwa?",
                "Jaka jedna rzecz najbardziej zmieniła twój sposób myślenia?",
                "Co według ciebie dzieje się po śmierci?",
                "Czy boisz się tego, że pewnego dnia możesz zapomnieć ważne wspomnienia?",
                "Gdybyś miała możliwość dowiedzieć się, kiedy umrzesz, czy chciałabyś to wiedzieć?",
                "Czy wierzysz w życie po śmierci?",
                "Czy uważasz, że wszystko w życiu dzieje się z jakiegoś powodu?",
                "Co byś zrobiła, gdybyś miała jeden dzień do końca życia?",
                "Gdybyś mogła wysłać list do siebie w przeszłości, co byś napisała?",
                "Czy zdarzyło ci się czuć, że żyłaś już ten moment wcześniej?",
                "Czy boisz się samotności?",
                "Jak chciałabyś zostać zapamiętana?",
                "Co według ciebie jest największym sensem życia?",
                "Jak myślisz, dlaczego czasami czujemy silne połączenie z niektórymi ludźmi?",
                "Czy miałaś kiedyś wrażenie, że jakieś miejsce lub osoba są ci dziwnie znajome?",
                "Gdybyś mogła spojrzeć na siebie oczami innej osoby, co chciałabyś zobaczyć?",
                "Co według ciebie definiuje człowieka – jego czyny czy myśli?",
                "Jaka była najodważniejsza decyzja, jaką kiedykolwiek podjęłaś?"
    ],
    life: [
        "Co według ciebie dzieje się po śmierci?",
        "Czy wierzysz w karmę?",
        "Czy boisz się samotności?",
		"Czy jest jakieś wydarzenie w twoim życiu, które sprawiło, że inaczej spojrzałeś na śmierć?",
		"Jak chciałbyś zostać zapamiętany przez bliskich?",
		"Gdybyś mógł dowiedzieć się dokładnej daty swojej śmierci, chciałbyś to wiedzieć?",
		"Czy uważasz, że życie ma jakiś głębszy cel, czy to my nadajemy mu sens?",
		"Jaka historia o śmierci lub pośmiertnym życiu zrobiła na tobie największe wrażenie?",
		"Gdybyś miał możliwość przeżyć jedno wydarzenie swojego życia jeszcze raz, co by to było?",
		"Czy kiedykolwiek czułeś, że coś większego czuwa nad twoim losem?",
		"Czy boisz się śmierci, czy raczej traktujesz ją jako coś naturalnego?",
		"Co sądzisz o idei reinkarnacji?",
		"Czy był moment w twoim życiu, gdy czułeś się naprawdę żywy?",
		"Gdybyś mógł powiedzieć coś jednej osobie, której już nie ma, co by to było?",
		"Co myślisz o koncepcji duszy – istnieje, czy to tylko iluzja?",
		"Jaka jest twoja ulubiona historia o kimś, kto zostawił po sobie ślad w historii?",
		"Co twoim zdaniem dzieje się po śmierci?",
		"Czy miałeś kiedyś doświadczenie bliskie śmierci lub coś, co cię do niej mocno zbliżyło?",
		"Czy był ktoś, kto odszedł zbyt wcześnie, i czujesz, że powinieneś był spędzić z nim więcej czasu?",
		"Czy istnieje dla ciebie coś warte poświęcenia własnego życia?",
		"Jaki był najbardziej przejmujący moment, kiedy czułeś, jak kruche jest życie?",
		"Gdybyś miał ostatnią szansę powiedzieć coś światu, co by to było?",
    ],
    love: [
        "Czy miłość jest dla ciebie najważniejszą wartością w życiu?",
        "Czy wierzysz w bratnie dusze?",
        "Jaki był najważniejszy moment w twoim życiu miłosnym?",
        
		"Czy wierzysz w miłość od pierwszego wejrzenia, czy raczej w miłość, która rodzi się z czasem?",			
		"Jaka była najpiękniejsza chwila, jaką przeżyłeś z kimś bliskim?",
		"Czy miłość wymaga poświęceń? Gdzie jest granica?",
			"Jakie wydarzenie w twoim życiu uświadomiło ci, że kochasz daną osobę?",
			"Czy był ktoś w twoim życiu, kogo nie doceniłeś, a później tego żałowałeś?",
			"Jaki był najbardziej romantyczny gest, jakiego doświadczyłeś?",
			"Czy myślisz, że miłość może trwać wiecznie?",
			"Jak myślisz, co jest kluczem do udanego związku?",
			"Czy uważasz, że dwie osoby mogą być sobie przeznaczone?",
			"Czy miłość to bardziej emocje czy decyzja?",
			"Jaka historia miłosna – filmowa lub prawdziwa – najbardziej cię poruszyła?",
			"Czy myślisz, że ludzie się zmieniają w związkach?",
			"Czy był moment w twoim życiu, kiedy myślałeś, że już nigdy się nie zakochasz?",
			"Jaka jest twoja definicja prawdziwej miłości?",
			"Czy w miłości ważniejsza jest szczerość czy czasem warto coś przemilczeć?",
			"Czy są osoby, których nigdy nie zapomnisz, nawet jeśli nie są już w twoim życiu?",
			"Czy miłość wymaga wzajemnego rozwoju, czy wystarczy akceptacja?",
			"Jaki był twój najważniejszy moment w budowaniu relacji z kimś?",
			"Czy uważasz, że jesteśmy zdolni kochać tak samo mocno więcej niż raz w życiu?",
    ],
    past: [
        "Jaka była najodważniejsza decyzja, jaką kiedykolwiek podjęłaś?",
        "Czy jest coś, czego żałujesz?",
        "Gdybyś mogła wysłać list do siebie w przeszłości, co byś napisała?",
		"Jaki moment z dzieciństwa najbardziej zapadł ci w pamięć?",
		"Czy jest jakaś rozmowa, którą przeżyłeś, a chciałbyś do niej wrócić i powiedzieć coś innego?",
		"Jakie miejsce z twojej przeszłości chciałbyś odwiedzić ponownie?",
		"Czy było coś, co kiedyś wydawało ci się ważne, a teraz widzisz to inaczej?",
		"Jaki zapach lub dźwięk od razu przywołuje w tobie wspomnienia?",
		"Gdybyś mógł napisać list do siebie z przeszłości, co byś w nim zawarł?",
		"Czy kiedykolwiek miałeś deja vu i jak je interpretujesz?",
		"Czy jest jakieś wydarzenie, które całkowicie zmieniło twoje życie?",
		"Jaki był twój największy sukces w dzieciństwie?",
		"Czy są ludzie z przeszłości, do których chciałbyś się odezwać, ale coś cię powstrzymuje?",
		"Jakie było najbardziej surrealistyczne doświadczenie, jakie przeżyłeś?",
		"Czy jest jakaś historia rodzinna, która przekazywana jest od pokoleń i wciąż cię fascynuje?",
		"Czy jest jakaś decyzja z przeszłości, której żałujesz?",
		"Jaki był najbardziej spontaniczny moment twojego życia?",
		"Czy był kiedyś moment, kiedy poczułeś się kompletnie wolny?",
		"Jaki był twój najzabawniejszy moment, o którym często wspominasz?",
		"Czy jest coś, czego nauczyłeś się dopiero po latach, a chciałbyś wiedzieć wcześniej?",
		"Jaki przedmiot, który kiedyś miałeś, chciałbyś odzyskać?",
		"Co było twoim pierwszym wielkim marzeniem?",
    ],
    mind: [
        "Czy uważasz, że myśli mają moc kształtowania rzeczywistości?",
        "Jakie pytanie o przyszłość chciałabyś znać odpowiedź?",
        "Czy wierzysz, że intuicja zawsze ma rację?",
        
		"Jakie emocje najtrudniej ci kontrolować?",
		"Czy zdarza ci się mieć wewnętrzne rozmowy ze sobą? O czym wtedy myślisz?",
		"Czy uważasz, że introwertycy i ekstrawertycy mogą się dobrze rozumieć?",
		"Czy kiedykolwiek poczułeś, że nikt nie jest w stanie zrozumieć twojego sposobu myślenia?",
		"Jakie słowa kogoś bliskiego na zawsze utkwiły ci w pamięci?",
		"Czy wierzysz, że emocje są w pełni pod naszą kontrolą?",
		"Jaką jedną rzecz w sobie najbardziej chciałbyś zrozumieć?",
		"Czy kiedykolwiek miałeś okres, w którym czułeś się zagubiony? Jak z niego wyszedłeś?",
		"Czy uważasz, że najtrudniejsze emocje są często najbardziej wartościowe?",
		"Jaki moment w życiu nauczył cię najwięcej o sobie?",
		"Czy masz jakieś mechanizmy radzenia sobie ze stresem?",
		"Czy kiedykolwiek czułeś, że twoje myśli są bardziej intensywne niż u innych?",
		"Czy uważasz, że lęk jest bardziej motywujący czy paraliżujący?",
		"Czy uważasz, że samoświadomość to dar czy przekleństwo?",
		"Jaką emocję najtrudniej ci opisać słowami?",
		"Czy uważasz, że można nauczyć się kontrolować własne myśli?",
		"Czy był moment, w którym emocje kompletnie cię zaskoczyły?",
		"Jak myślisz, czy myśli mogą mieć fizyczny wpływ na ciało?",
		"Czy kiedykolwiek przeżyłeś coś, co zmieniło sposób, w jaki postrzegasz emocje?",

    ],
	    brainroot: [
        "Czy jest coś, co chciałbyś zmienić w swoim sposobie myślenia, ale nie potrafisz?",
"Gdybyś mógł wrócić do jednego dnia w swoim życiu i przeżyć go jeszcze raz, jaki by to był dzień?",
"Jakie było twoje najtrudniejsze pożegnanie i dlaczego?",
"Czy istnieje książka, film lub piosenka, które zmieniły twój sposób postrzegania świata?",
"Jaki jest twój największy lęk, o którym rzadko mówisz?",
"Czy miałeś kiedyś wrażenie, że pewne wydarzenia w twoim życiu miały miejsce z jakiegoś powodu?",
"Co jest dla ciebie bardziej wartościowe: stabilizacja czy przygoda?",
"Czy kiedykolwiek miałeś moment, kiedy musiałeś podjąć decyzję, która całkowicie zmieniła twoją przyszłość?",
"Jak myślisz, czy nasze wspomnienia są bardziej kształtowane przez rzeczywistość czy przez to, jak chcemy je pamiętać?",
"Czy wierzysz, że każdy człowiek nosi w sobie jakąś tajemnicę?",
"Jakie doświadczenie w twoim życiu nauczyło cię najwięcej o samym sobie?",
"Czy istnieje coś, co zawsze chciałeś powiedzieć komuś, ale nigdy się na to nie odważyłeś?",
"Jakie jest twoje najbardziej osobiste marzenie, którego nigdy nikomu nie powiedziałeś?",
"Gdybyś mógł opisać siebie jednym cytatem, co by to było?",
"Czy zdarzyło ci się kiedyś mieć intuicję, która okazała się prawdziwa?",
"Jak myślisz, czy bardziej kształtują nas sukcesy czy porażki?",
"Czy uważasz, że każda osoba ma w sobie coś nieodgadnionego?",
"Jaki jest najbardziej niewytłumaczalny moment, jaki przeżyłeś?",
"Czy kiedykolwiek poczułeś się zupełnie oderwany od rzeczywistości, jakbyś patrzył na świat z innej perspektywy?",
"Gdybyś mógł cofnąć się w czasie i zmienić jedną decyzję, co by to było?",
"Jaka była najważniejsza lekcja, jakiej nauczyło cię życie?",
"Czy jest jakaś rozmowa z przeszłości, do której chciałbyś wrócić?",
"Jak myślisz, czy nasze emocje są w pełni pod naszą kontrolą?",
"Czy masz w swoim życiu kogoś, kto znacząco wpłynął na twój sposób myślenia?",
"Co najbardziej cię fascynuje w ludzkiej naturze?",
"Jakie pytanie najbardziej chciałbyś, żeby ktoś ci zadał?",
"Czy był moment w twoim życiu, kiedy poczułeś, że znalazłeś swoje miejsce na świecie?",
"Czy wierzysz, że każda emocja jest potrzebna, nawet te negatywne?",
"Co sprawia, że czujesz się naprawdę spełniony?",
"Czy miałeś kiedyś wrażenie, że los prowadzi cię w określonym kierunku?",
"Jaka jest najważniejsza rzecz, jaką nauczyłeś się o relacjach międzyludzkich?",
"Czy są rzeczy, które wydawały ci się nieistotne, a po latach okazały się bardzo ważne?",
"Co według ciebie sprawia, że niektóre wspomnienia zostają z nami na zawsze?",
"Jakie pytanie sam sobie najczęściej zadajesz?",
"Czy kiedykolwiek miałeś przeczucie, które zmieniło twoje decyzje?",
"Czy istnieje wspomnienie, które często do ciebie wraca i nie wiesz dlaczego?",
"Jakie momenty w twoim życiu najbardziej ukształtowały twoją osobowość?",
"Gdybyś mógł na jeden dzień zamienić się w inną osobę, kogo byś wybrał i dlaczego?",
"Jak myślisz, czy to my tworzymy swoje przeznaczenie, czy jest ono z góry ustalone?",
    ]
};

function drawQuestion(category) {
    const questionBox = document.getElementById("question-box");
    const randomIndex = Math.floor(Math.random() * questions[category].length);
    questionBox.innerHTML = `<p>${questions[category][randomIndex]}</p>`;
    questionBox.style.display = "block";
}